### PR TITLE
anonymous user handling

### PR DESCRIPTION
**Pull request by HanilJain**
fixed the issue here anonymous user was able to view private reported issue in latest activity.

https://github.com/HanilJain/BLT/blob/64310e4fe217b7de992d257c520db781e3856c77/website/views.py#L135C1-L138C98

### CODE REVIEW

**Review by DonnieBLT — COMMENTED** [review]
Looks good. How about the api can you please check other places this might happen?

**Comment by HanilJain** [comment]
**anonymous use handling in API added :**  
in the following API
/api/v1/issues/
/api/v1/userissues/
/api/v1/search

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Can you please add an automated test to this because it's an important security feature.

**Comment by HanilJain** [comment]
@DonnieBLT  Added automated test for the API

**Review by fredfalcon — APPROVED** [review]

**Review by DonnieBLT — APPROVED** [review]

**Comment by HanilJain** [comment]
@DonnieBLT is it ready to be merged then ?

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
