### PR TITLE
Issue 1819 Issue with button visiblity in light mode

### PR DESCRIPTION
**Pull request by Sarthak5598**

### CODE REVIEW

**Comment by Sarthak5598** [comment]
@DonnieBLT please merge!

**Comment by DonnieBLT** [comment]
Can you send a screenshot of what it looks like with these changes thanks

**Comment by Sarthak5598** [comment]
Screenshot 2024-02-29 222109

**Comment by DonnieBLT** [comment]
Thanks it seems like the QR code has no way to close it. Can you please add a close button to the model, and if the address is none or empty, let's not show the QR code.

**Comment by Sarthak5598** [comment]
Okay ! But if user doesn't have the address the tip button would look like its not working ,Maybe we can show a message instead of showing QR ?
and also If possible can you make it a separate task ? 
Because I have to make changes in both the tip button

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
