### PR TITLE
fix: Top hunts UI error message is not at center of screen for small screens #1267

### LINKED ISSUE #1267: Bug: Top hunts UI error message is not at center of screen for small screens
**Describe the bug**
The "No ongoing bughunts" error is not at center for small screens

**To Reproduce**
1. Go to BLT home page
2. make the screen width less than 526 px

**Expected behavior**
It should be at center of the page for every screen width

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by shubham-200315**
## Before
Screenshot 2023-06-15 231311

## After

Screenshot 2023-06-15 231516

## Made changes in  **index.html**  and **style.css** file

@AtmegaBuzz Please review and merge.

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
Thanks for the PR @shubham-200315. I would suggest use tailwind css only to solve this case you just need to add class in the error container for justify-center

**Comment by shubham-200315** [comment]
Hey @AtmegaBuzz thanks for suggestion, It was a great help.
Deleting all the changes and making a new PR

**Comment by shubham-200315** [comment]
### Removed all the changes and added 
```
<div class="w-full flex justify-center">
     <p class="text-red-500">No ongoing hunt's found.</p>
</div>
```

PTAL @AtmegaBuzz

**Comment by AtmegaBuzz** [comment]
@DonnieBLT LGTM can be merged

**Review by DonnieBLT — APPROVED** [review]

**Comment by DonnieBLT** [comment]
Thank you!

**Pull request merged**
