### PR TITLE
Simple Comments section on the issues page

### PR DESCRIPTION
**Pull request by mohitanand001**

### CODE REVIEW

**Comment by seanauriti** [comment]
Thanks so much, can you please add the migration too?

**Comment by farziengineer** [comment]
Looks like there is service outage on GitHub. I'll update asap.
Thanks

**Comment by farziengineer** [comment]
Hey I've added the migration files.

**Comment by seanauriti** [comment]
Great, can you please remove the .pyc files, those will be on the server already.

**Comment by seanauriti** [comment]
thank you!

**Comment by farziengineer** [comment]
No problem :+1:

**Pull request merged**
