### PR TITLE
Enhancement: Bug Details Page; Revision 8

### PR DESCRIPTION
**Pull request by CodeWithBishal**
Marked with black are the changes that to be done by @thedudeontitan  

Thank You!

Screenshot 2024-06-14 at 10 05 38 PM

### CODE REVIEW

**Comment by thedudeontitan** [comment]
### Implemented screenshot carousel and updated the description and details

### Before: 


### After:

**Comment by thedudeontitan** [comment]
###Change in the interaction buttons
Commit: https://github.com/OWASP-BLT/BLT/pull/2355/commits/8b03649d37cd3ee1210561f88d5d0d300ab28ac4

###Before:


###After:

**Comment by thedudeontitan** [comment]
Fixes #2291 

Collaborated with @CodeWithBishal on this PR.

**Comment by CodeWithBishal** [comment]
This closes #2271 #2272 #2273 #2274 #2275

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
