### PR TITLE
API search domain/label/user functioning

### LINKED ISSUE #1724: Bug: TypeError at /api/v1/search/
**Describe the bug**
when type is changed to domain , User. It gives an error TypeError

**To Reproduce**
1. Go to 'base_url/api/v1/search/'
2. Click on 'type'
3. change down to 'domain/user'
4. search anything in it
5. See error

**Expected behavior**
should show the revelant data

**Screenshots**
type error bug

### PR DESCRIPTION
**Pull request by HanilJain**
## Fixed #1724 

- Label Listed in the option of search.
- Made functional Domain / User / Label

### CODE REVIEW

**Comment by HanilJain** [comment]
@DonnieBLT can you please review ?

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Can you add the front end part to add labels to domains too?

**Review by DonnieBLT — COMMENTED** [review]
This also requires the front end to add the label

**Review by DonnieBLT — APPROVED** [review]

**Comment by DonnieBLT** [comment]
Thanks!

**Pull request merged**
