### PR TITLE
fix sanitization for 1353

### PR DESCRIPTION
**Pull request by manthan0x23**
#1353 fix

### CODE REVIEW

**Comment by JisanAR03** [comment]
can you please stop work on bootstrap.js? I already fixed those and am just waiting to confirm other PR then i will make the pr again (I didn't make those PR because of conflict issue),

**Comment by manthan-sharma-23** [comment]
Yeah sure mate ! ,didn't know that.

**Comment by JisanAR03** [comment]
> Yeah sure mate ! ,didn't know that.

@manthan-sharma-23  thank you so much😊

**Comment by JisanAR03** [comment]
the code should like :
image
because title could be anything and we have to apply condition to them ,, I already solve this issue just didn't make pull request because of my some PR are pending and this update is depend on pending PR

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
