### PR TITLE
Allow user to update crypto_address from profile page #1866

### PR DESCRIPTION
**Pull request by Sarthak5598**
#1881

### CODE REVIEW

**Review by DonnieBLT — DISMISSED** [review]
The issue also happens on the user profile

**Comment by Sarthak5598** [comment]
No, user profile don't have this issues it's working perfectly , the only reason we had issue was because leader was not updating so, I used request.user to solve the issue

**Comment by Sarthak5598** [comment]
I added request.user here too, even though it was still working . It is working fine now !

**Comment by Sarthak5598** [comment]
yes , thats my bch address

**Review by DonnieBLT — CHANGES_REQUESTED** [review]

**Comment by Sarthak5598** [comment]
@DonnieBLT I made some new changes and now its working fine can you reopen this branch ?

**Comment by Sarthak5598** [comment]
image
I used different id for each user in leaderboard now we have no issues

**Comment by Sarthak5598** [comment]
https://github.com/OWASP-BLT/BLT/pull/1929
made  new pr check it out !!!!

**Pull request closed without merging**
