### PR TITLE
updated and fixed django-allauth.

### PR DESCRIPTION
**Pull request by Deus1704**
This PR is for #1606 
I have updated the Django-allauth to 0.60.1 and the corresponding requirement dj-rest-auth to 5.0.2 and included the middleware necessary for the new allauth to function properly.

### CODE REVIEW

**Review by DonnieBLT — DISMISSED** [review]

**Comment by Deus1704** [comment]
@DonnieBLT Sir I think I get why the Django Test/build is failing. The issue is that the api endpoint /auth/registration is returning No Content code=204, but the console registers the user's credentials.
image

 Ideally the api should be returning the key. I am trying to understand the apis and will find a fix.

Currently:
image

Ideally:
image

**Comment by DonnieBLT** [comment]
@Deus1704 we may have do update this at the same time - https://github.com/OWASP/BLT/pull/1594

**Comment by Deus1704** [comment]
> @Deus1704 we may have to update this at the same time - #1594

Yeah, this would close both the PRs at the same time.

**Review by DonnieBLT — APPROVED** [review]
Thank you!

**Pull request merged**
