### PR TITLE
Fixed the broken UI at Report a Bug

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**
Issue #1683 

**BEFORE**

image

**AFTER**

image

- I have put the images inside a box matching the theme of the entire website.
- The images are horizontally scrollable, which reduces the box size and makes the website looks clean.
- I have added a scale hovering effect on images.

### CODE REVIEW

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
How come some of the icons looks squished like the third one is there a way to fix that?

**Comment by Prakhar-Shankar** [comment]
> How come some of the icons looks squished like the third one is there a way to fix that?

Sure sir, I will look into it and will commit the changes

**Comment by Prakhar-Shankar** [comment]
I have made the necessary changes please review it sir @DonnieBLT .
image

**Comment by DonnieBLT** [comment]
Can we not have a border or scroll bar please and also make the icons square (rounded corners is fine)

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Please update.

**Comment by Prakhar-Shankar** [comment]
> Please update.

Yes sir I am working on it.

**Comment by Prakhar-Shankar** [comment]
@DonnieBLT 
Sir, I have updated the UI 
image

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
