### PR TITLE
Contributors to users

### LINKED ISSUE #2884: Migrate all the contributors to users and make the page work based on a tag

### PR DESCRIPTION
**Pull request by krrish-sehgal**
Fixes #2884.

Changes: 
"Users" now default shows contributors unless the other tag is selected 
contributors are always loaded from json 
other tags are loaded by flitering from profile section 
"Contributors" option loads users/tag=contributors page
contributor_view changed to contributor_detail_view for the More info option on contributor page 
the card for all contributors and other tags is synced in their design.

https://github.com/user-attachments/assets/e572271d-5aae-47be-8762-093cd400893c

### CODE REVIEW

**Comment by krrish-sehgal** [comment]
@DonnieBLT this PR could close #2884, could you please give it a review?

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
I mean for these contributors to be linked to users on the site. Can you map each user to the contributor?

**Comment by krrish-sehgal** [comment]
okay that will require me to personally contact the contributors and get their blt usernames as there is no direct way to map hard coded contributor names to their blt user profiles , however is the UI meets what you had in mind? like when on the users page ,  the name of the user i clicked , the user profile of that contributor will get opened

**Comment by krrish-sehgal** [comment]
> okay that will require me to personally contact the contributors and get their blt usernames as there is no direct way to map hard coded contributor names to their blt user profiles , however is the UI meets what you had in mind? like when on the users page , the name of the user i clicked , the user profile of that contributor will get opened

@DonnieBLT sir , i had a pending doubt here.
thanks.

**Comment by krrish-sehgal** [comment]
> You can try searching the users and map them that way first I think most of them have a BLT username

Sure @DonnieBLT sir, i have made the changes to it and linked contributor profiles whose names were'nt ambiguous and could be found through search.

**Pull request closed without merging**
