### PR TITLE
Adding translate button

### PR DESCRIPTION
**Pull request by daemon-reconfig**
solves  https://github.com/OWASP/BLT/issues/680

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
Awesome looks good, just need little margin left of 2 - 3 px can you add that

**Comment by daemon-reconfig** [comment]
sure

**Comment by daemon-reconfig** [comment]
I have added margin to left side 
Screenshot 2023-08-24 at 12 14 33 AM


**How it works**
by simply choosing the language the user can change the language.
Screenshot 2023-08-24 at 12 16 08 AM

**Comment by AtmegaBuzz** [comment]
LGTM @DonnieBLT

**Comment by DonnieBLT** [comment]
Can you please make it look like a button and not an input field? Also can you remove the powered by google logo?

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Please see comment

**Comment by daemon-reconfig** [comment]
These changes cannot be made although i can try making it look like a button but the "Powered by google" text cannot be removed as it is the USP of google.
Although i doubt i can make it in a button as it is a script provided by google.
if there are any alternatives that do fit your requirements, please do let me know

**Comment by daemon-reconfig** [comment]
I did try making it like a button but it did not work as intended.

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Can you make it look like the last example here and please show a screenshot https://www.w3schools.com/howto/howto_google_translate.asp

**Comment by daemon-reconfig** [comment]
Screenshot 2023-08-24 at 10 07 02 PM
does this work?

**Comment by daemon-reconfig** [comment]
Screenshot 2023-08-24 at 10 11 22 PM

There

**Comment by DonnieBLT** [comment]
Did you commit the change?

**Comment by DonnieBLT** [comment]
Yes that looks good

**Comment by daemon-reconfig** [comment]
I waited for your approval let me do so now

**Review by DonnieBLT — APPROVED** [review]
Thank you!

**Comment by daemon-reconfig** [comment]
now I will work on more good first issues hehe. by the way can I improve the UI here?
Screenshot 2023-08-24 at 10 35 19 PM

**Pull request merged**
