### PR TITLE
Tweet Feature 

### PR DESCRIPTION
**Pull request by HanilJain**
### Added Feature #1239 

using **tweepy** library this feature has been added.

BEARER_TOKEN
APP_KEY
APP_KEY_SECRET
ACCESS_TOKEN
ACCESS_TOKEN_SECRET
needed to be set in the .env file

here is an example video 

https://github.com/OWASP/BLT/assets/119354421/6d943dc3-3693-4bea-9457-ba53a841c092

### CODE REVIEW

**Comment by HanilJain** [comment]
@DonnieBLT could you please review

**Comment by DonnieBLT** [comment]
Can you please add instructions to get those values?

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
I think we already had sent to Twitter somewhere else in the code. Can you check where that is and see if that's working and maybe updates at that section

**Comment by HanilJain** [comment]
> I think we already had sent to Twitter somewhere else in the code. Can you check where that is and see if that's working and maybe updates at that section

yes there was but not was used anywhere.
and dose not seems to contain API v2 and complicated 
So I removed it.
is it okay ?

**Comment by HanilJain** [comment]
> Can you please add instructions to get those values?

https://developer.twitter.com/en/docs/authentication/oauth-1-0a/api-key-and-secret

https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
