### PR TITLE
CSS Card - Types of bugs

### PR DESCRIPTION
**Pull request by sid22**
Added examples for types of bugs using search and design changes.

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
The search functionality does not filter by bug type!

**Comment by goyal-sidd** [comment]
Oh!. I will fetch from db then.

**Comment by goyal-sidd** [comment]
@jajodiaraghav sir, I have built upon the search made by you and added for labels and fixed links in cards. Please review.

**Review by fredfalcon — APPROVED** [review]

**Comment by jajodiaraghav** [comment]
Please do not merge this. Working on top of it.

**Pull request closed without merging**
