### PR TITLE
fix security issue #1329

### PR DESCRIPTION
**Pull request by JisanAR03**
fix - #1329 
issue : "self.request.META.get("HTTP_REFERER")" gets the location "/report" , which is also declares it, in  the variable 'redirect_url'
screenshot : 
image

### CODE REVIEW

**Review by DonnieBLT — APPROVED** [review]

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
please check this against the tests

**Comment by JisanAR03** [comment]
> please check this against the tests

ok sir

**Comment by DonnieBLT** [comment]
amazing work - I double checked everything and so far these are the only ones remaining - https://github.com/OWASP/BLT/labels/security thank you!

**Comment by JisanAR03** [comment]
> amazing work - I double checked everything and so far these are the only ones remaining - [ security](https://github.com/OWASP/BLT/labels/security) thank you!

and please provide me the screenshot of security issue which is left

**Comment by DonnieBLT** [comment]
> > amazing work - I double checked everything and so far these are the only ones remaining - [ security](https://github.com/OWASP/BLT/labels/security) thank you!
> 
> and please provide me the screenshot of security issue which is left

they are all attached

**Comment by JisanAR03** [comment]
> > > amazing work - I double checked everything and so far these are the only ones remaining - [ security](https://github.com/OWASP/BLT/labels/security) thank you!
> > 
> > 
> > and please provide me the screenshot of security issue which is left
> 
> they are all attached

ok sir ☺

**Pull request closed without merging**
