### PR TITLE
Add remaining dynamic variables to templates

### LINKED ISSUE #1073: Make sure all templates are using the new dynamic variables
For 
PROJECT_NAME
DOMAIN_NAME
FQDN
There are about 38 templates to replace the word “bugheist” in with these new variables

### PR DESCRIPTION
**Pull request by Kej-r03**
Fixes #1073 
I guess now no other template html file remains with this issue

### CODE REVIEW

**Review by fredfalcon — CHANGES_REQUESTED** [review]
Any place the word bugheist appears has to be a variable.

**Review by fredfalcon — CHANGES_REQUESTED** [review]
thanks for this, I added a few changes and then we're good to merge.

**Comment by Kej-r03** [comment]
Yes, I will make the changes

**Comment by Kej-r03** [comment]
@fredfalcon I have made the changes, please take a look

**Review by fredfalcon — APPROVED** [review]
Great work!  Thank you

**Comment by Kej-r03** [comment]
@fredfalcon Can I resolve the 2 pending conversations so that it can be merged?

**Pull request merged**
