### PR TITLE
Feature: Contributor Activity Dashboard

### LINKED ISSUE #1705: Project: Weekly contributor report
Generates a report that is sent to Slack Saturday at 1pm EST
Shows contributor github username, commits, issues opened, issues closed, assigned issues, pull requests, total comments and more

### PR DESCRIPTION
**Pull request by JisanAR03**
**Implemented:**  We've added a dashboard that shows what everyone has been up to in the last week. This includes all the work like commits, new issues, closed issues, tasks assigned, pull requests, and comments.

**What to do:**

- Add a new line in your .env file that looks like this: GITHUB_TOKEN=your_github_access_token_here.
- run `pip install django-crontab` for install crontab in django
- and run `python manage.py crontab add` & `python manage.py crontab show` for start the cron job
- Go to the Contributor Stats page from the menu to see the latest updates from all contributors.

**Why It's For:**

1. It uses data from GitHub to show what's happening in the project.
2. It's designed to be easy to look at and understand.
3. It helps everyone see the impact of their work and others.

@DonnieBLT sir . Please review this one and provide some feedback. fix #1705 and #1870

### CODE REVIEW

**Comment by HanilJain** [comment]
@JisanAR03 Hi, I think I can help you here in workflow error if you don't mind, it must be due to python error. You can parse the pr first and then find an appropriate call for the author.

**Comment by JisanAR03** [comment]
> This looks great. One concern I have is that it may hit the rate limit, if many people view the page, so what we can maybe do is create another endpoint that can process the task like this, and then save it to the database, It will also speed up the page as well. Then I can setup a cron task to call that url. Another alternative would be to make it a Django management command and then can also be setup to run on a schedule.

ok sir sure.,.I will update this one

**Comment by JisanAR03** [comment]
> @JisanAR03 Hi, I think I can help you here in workflow error if you don't mind, it must be due to python error. You can parse the pr first and then find an appropriate call for the author.

thank you . let me update the pr first ,,then you can help me for this issue

**Comment by JisanAR03** [comment]
@DonnieBLT sir , I updated this PR , can you please review this one.

**Comment by AtmegaBuzz** [comment]
yes, we can make it as a cron tab job that runs everyday and saves data to the database to not slow down the page

**Review by DonnieBLT — APPROVED** [review]
looks great, I removed the django-cron as we don't have access to cron on Heroku and we can setup a scheduler to run the management command instead which works.

**Pull request merged**
