### PR TITLE
Generate Data for Monthly LeaderBoard

### LINKED ISSUE #1106: Monthly Leaderboard is showing global leaderboard results

### PR DESCRIPTION
**Pull request by solo-daemon**
fix #1106 

@fredfalcon the api for leader board was already there but was not generating the all the required fields

### CODE REVIEW

**Comment by solo-daemon** [comment]
This pr is ready for review

**Review by fredfalcon — CHANGES_REQUESTED** [review]
Can you please show a screenshot of the before and after?

**Comment by solo-daemon** [comment]
before : 
Screenshot 2023-03-13 004002

after : 
Screenshot 2023-03-13 003954

**Comment by AtmegaBuzz** [comment]
I would suggest add the pagination to the response just like before, because in prod there are too many users and it will slow down the api

**Comment by solo-daemon** [comment]
@AtmegaBuzz ok adding the commit shortly .

**Comment by solo-daemon** [comment]
@AtmegaBuzz done

**Comment by AtmegaBuzz** [comment]
lgtm, Thanks @solo-daemon

**Review by fredfalcon — APPROVED** [review]

**Pull request merged**
