### PR TITLE
Min-height to pages with less content

### PR DESCRIPTION
**Pull request by ManishBisht777**
Added min-height to the pages with less content

### changes

Added min-height to :

1) `signup.html`
2) `search.html`
3) `leaderboard.html`

I am using prettier to I ended up formatting the code as well :)

### CODE REVIEW

**Review by fredfalcon — CHANGES_REQUESTED** [review]
Can you just change the min height part and not the other code?

**Comment by ManishBisht777** [comment]
actually, I am using a formatter so I did end up formatting the files. i will make the changes

**Comment by ManishBisht777** [comment]
@fredfalcon hope it is good now :)

**Review by fredfalcon — APPROVED** [review]

**Comment by fredfalcon** [comment]
Thank you!

**Pull request merged**
