### PR TITLE
Removed inline CSS

### PR DESCRIPTION
**Pull request by sid22**
I have removed inline CSS from all the template html files. The some places left are dynamic. 
If I have missed anything kindly tell me.
Solves #236

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
> I have removed inline CSS from **all** the template html files

Are you sure there aren't anymore inline css present?
I bet there are hundreds of other places you missed. You could fix those in a different commit/PR if you want.

**Comment by goyal-sidd** [comment]
Ok, I will check again in using Find.

**Comment by goyal-sidd** [comment]
He @jajodiaraghav should I also work on inline style tags which have dynamic values. 
Like here in the screenshot:-
jajo

**Comment by jajodiaraghav** [comment]
@goyal-sidd No. You do not have to remove them. Leave them as is

**Comment by goyal-sidd** [comment]
I have removed most of style tags, the ones remaining are that are with dynamic entries or are single.

**Comment by jajodiaraghav** [comment]
This looks much better. Thanks @goyal-sidd 
Yes, all inline css is removed :+1:

**Review by fredfalcon — APPROVED** [review]

**Pull request merged**
