### PR TITLE
Making the comment section mobile responsive

### LINKED ISSUE #1383: Bug: Comment section is not mobile responsive
**Describe the bug**
Comment section is not mobile responsive

**To Reproduce**
1. Go to https://www.bugheist.com/issue/2129/ (you can go to any issue number)
2. Add a comment
3. Inspect the page and check responsiveness

**Expected behavior**
In mobile view, elements of comment section should not overflow out of the window.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**
Closes #1383 

I have used tailwind to fix this issue.

Screenshots: 

Before: 

image

After:

image

### CODE REVIEW

**Comment by Prakhar-Shankar** [comment]
@DonnieBLT Idk why but commits from my different branches are also visible here, although respective file changes are not reflected in this PR. What might be the reason for this? Should I close this PR and open a new one?

**Comment by DonnieBLT** [comment]
@Prakhar-Shankar this doesn't look right, the card should wrap the comment, currently it looks like it overlaps it

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
the card should wrap around the comment, currently it looks like it overlaps

**Comment by Prakhar-Shankar** [comment]
I am facing some problem, I am closing this PR and opening a new one.

**Pull request closed without merging**
