### PR TITLE
updated twitter logo

### LINKED ISSUE #1404: Bug: Updating twitter logo in footer
**Describe the bug**
The site is still showing old twitter logo.

**To Reproduce**
1. Go to https://www.bugheist.com/
2. Scroll down 
3. Check out the logo in footer

**Expected behavior**
Logo should be updated to X.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**
Closes #1404 
The logo has beed updated

Previously - 
image

After changes- 
image

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
LGTM, Thanks for the PR @Prakhar-Shankar

**Comment by just-ary27** [comment]
@Prakhar-Shankar can you update your branch?

**Comment by DonnieBLT** [comment]
Yeah it seems to thrown an error when merging

**Comment by Prakhar-Shankar** [comment]
I have updated it rn.

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
