### PR TITLE
Resolved Integrity and ProjectDoesNotExist Errors

### PR DESCRIPTION
**Pull request by tsu-ki**
Fixes issue: https://github.com/OWASP-BLT/BLT/issues/3009

https://github.com/user-attachments/assets/746a5a8e-5f82-4e06-ab2f-d4079c3b3daf

### CODE REVIEW

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
see change request

**Comment by tsu-ki** [comment]
> if a project with the slug exists we want to throw an error not increment

oh, I'll make the required changes then, thank you

**Comment by tsu-ki** [comment]
@DonnieBLT is this solution correct?

https://github.com/user-attachments/assets/78b1eda1-aaeb-4ee9-8f7d-cc8db0065140

**Review by DonnieBLT — DISMISSED** [review]

**Comment by tsu-ki** [comment]
@DonnieBLT Can you please merge the PR? thank you so much

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
