### PR TITLE
Fixed the invisible "Sponsor a price" submit button 

### PR DESCRIPTION
**Pull request by officialarmannqureshi**
Problem: Invisible sponsor submit button.
issue 01

Solution :
image

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
Thanks for the PR! @officialarmannqureshi but this issue is already solved in pr #1395. I think you didn't pulled the latest code from main

**Comment by officialarmannqureshi** [comment]
> Thanks for the PR! @officialarmannqureshi but this issue is already solved in pr #1387 . I think you didn't pulled the latest code from main

Hi,
I have improved the UI also.
Before :
image

After:

image

**Comment by officialarmannqureshi** [comment]
@AtmegaBuzz Review this also !

**Comment by AtmegaBuzz** [comment]
your PR is related to Sponsor a Price button improved UI, so only change the css that leads to this result. I see there are lot of unnecessary changes that you've made can you please revert all of those or create new PR that include specific changes related to the UI you are improving

**Pull request closed without merging**
