### PR TITLE
fix: fixed hyperlink issue in signup email

### LINKED ISSUE #2934: Email for verification always ends up in spam and contains long verification link.
Tried creating an account with two different accounts, ends up in spam
Image

  
A suggestion would be to add an href tag instead of copying that long string containing the token  
and pasting it in the browser. 
This would be better from a UX standpoint imo.

### PR DESCRIPTION
**Pull request by 1010varun**
fixes: #2934

### CODE REVIEW

**Comment by 1010varun** [comment]
So what should I can do to make it a link

**Comment by 1010varun** [comment]
Yess, yesterday I tried the same thing but I didn't get the function from where this is being called. Can you please help me in this?

**Comment by 1010varun** [comment]
Done with adding the .html template. Got the solution in allauth docs

**Review by DonnieBLT — DISMISSED** [review]

**Comment by 1010varun** [comment]
@DonnieBLT just forgot to run pre-commit previously, can you please approve once one

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
