### PR TITLE
Badge-system

### LINKED ISSUE #2885: Create badges for users that can be earned automatically or given from a mentor
Have a badge for mentor
Have a badge for copilot user 
Have a badge for openai
Have a badge for a GSOC student 
Have badges be nicely designed

### PR DESCRIPTION
**Pull request by krrish-sehgal**
fixes #2885

The Badges can be added by the  user with the mentor badge only and that mentor badge can only be to a person through a migration file for now. ( I have hard coded user "donnie" for the mentor in migration file).

Currently the badges are without any icon but i have attached the demo where i have created 2-3 badge icons to show how it will look like.

Please find my ideas for managing the images and automatic earning of badges below in comments.

https://github.com/user-attachments/assets/379f6c68-0194-4f96-ac60-0b8a4a26b244

### CODE REVIEW

**Comment by krrish-sehgal** [comment]
Hi @DonnieBLT sir,

Regarding the badge icon image, currently, I am storing them locally within the media folder and accessing them from there. However, for scalability and better management, I wanted to confirm the preferred approach for storing these images. A cloud storage option like Amazon S3 seems to be the most suitable solution, but I would appreciate your thoughts on what aligns best with your plans and long-term strategy.

For the automatic badge earning mechanism, I suggest using GitHub webhooks. We can configure them to send pings to our server whenever certain actions occur in our repository (e.g., creating a PR, merging a PR, and others). From there, we can process the data in our Django codebase, extract relevant details from the webhook payload, and generate a new badge accordingly, would appreaciate your thoughts on this.

On a different note, This PR would allow me to proceed with the blue sky issue. Could you please confirm which issue you would prefer me to prioritize? I'll make sure to focus on the most critical one first.

Thanks.

**Comment by krrish-sehgal** [comment]
Also feel free to suggest any changes in the current implementation. 
thanks.

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
This looks great - I think we can simplify it slightly by having a ManyToMany field  on the UserProfile for badges =

**Comment by krrish-sehgal** [comment]
> This looks great - I think we can simplify it slightly by having a ManyToMany field on the UserProfile for badges =

Sure , on it.

**Review by DonnieBLT — APPROVED** [review]

**Comment by krrish-sehgal** [comment]
> This is approved

Thanks, I'll work on the failing test case.

**Comment by krrish-sehgal** [comment]
> Cool, and regarding the badge icons, it's ok to have them in a static folder for now and good idea about the webhooks.

okay sir.

**Pull request merged**
