### PR TITLE
Set up pre-commit

### PR DESCRIPTION
**Pull request by arkid15r**
This PR is an initial step to address #1805 

It contains pre-commit config, dependency updates and Github workflow config. All other changes have been generated automatically by `pre-commit run -a` command.

I took the liberty and set the max-width for the project to a reasonable default 100. Please let me know if that's something that needs to be adjusted.

I'll be filing several subsequent PRs to address ruff ignore rules I added here.

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
LGTM!

**Review by DonnieBLT — APPROVED** [review]
Thank you!

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Looks like something slipped in before we got a chance to merge this and there's a conflict. Can you please take a look?

**Review by arkid15r — COMMENTED** [review]
Synced with current main. PTAL!

**Review by DonnieBLT — APPROVED** [review]
nice work, thank you

**Pull request merged**
