### PR TITLE
Display language-name in the language-select menu

### LINKED ISSUE #1403: Bug: Language names not displayed in the footer menu
Language names are not displayed in the Footer Menu(Language Flag icon).

image

### PR DESCRIPTION
**Pull request by Pandey-SaurabhP**
Language name were not displayed in the language-select menu in footer, adding support for displaying the same.

Closes https://github.com/OWASP/BLT/issues/1403

### CODE REVIEW

**Comment by Pandey-SaurabhP** [comment]
Fixes : https://github.com/OWASP/BLT/issues/1403

**Comment by Pandey-SaurabhP** [comment]
After fixing : Languages are visible

image

**Comment by AtmegaBuzz** [comment]
LGTM, Thanks for the PR! @Pandey-SaurabhP

**Review by DonnieBLT — APPROVED** [review]

**Comment by DonnieBLT** [comment]
Thank you!

**Pull request merged**
