### PR TITLE
Support for API rate throttling

### PR DESCRIPTION
**Pull request by AtmegaBuzz**
Fix: Add API Rate Limiter using django rest framework throttling https://github.com/OWASP/BLT/issues/1234

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
this test fixes are included in report bug page pr, will be automatically fixed on its merge

**Review by fredfalcon — CHANGES_REQUESTED** [review]
can you please fix the tests?

**Comment by AtmegaBuzz** [comment]
@fredfalcon done with this feature, can be merged

**Review by DonnieBLT — APPROVED** [review]

**Comment by AtmegaBuzz** [comment]
@DonnieBLT is there any change i need to do here ? i cannot see the requested changes

**Review by fredfalcon — APPROVED** [review]

**Comment by AtmegaBuzz** [comment]
stats1
stats2

**Pull request merged**
