### PR TITLE
Fix style error in /index leaderboard section

### PR DESCRIPTION
**Pull request by jajodiaraghav**

### CODE REVIEW

**Comment by seanauriti** [comment]
Can you please fix the merge?

**Comment by jajodiaraghav** [comment]
Why is this closed? Has the issue been fixed?

**Comment by seanauriti** [comment]
It changed with the recent update and needs some refactoring.  Can you please pull again?

**Comment by jajodiaraghav** [comment]
Yes sure! Should I create a new PR?

**Comment by seanauriti** [comment]
Yes please.

**Pull request closed without merging**
