### PR TITLE
Front-end changes in main page and sponsor page

### PR DESCRIPTION
**Pull request by Roboneet**
screen shot 2017-06-04 at 6 54 56 pm
screen shot 2017-06-04 at 6 59 25 pm
screen shot 2017-06-04 at 6 59 47 pm
screen shot 2017-06-04 at 6 59 49 pm
#142

### CODE REVIEW

**Comment by farziengineer** [comment]
Hello @Roboneet , I think the "Attach Screenshot"  label  should be removed because, the "Upload Screenshot" looks sufficient.  
Thanks

**Comment by seanauriti** [comment]
Thank you!  Looks good. Would you please fix the merge conflict and make sure the tests.py works too?

**Comment by Roboneet** [comment]
I've removed the "attach screenshot" label and fixed conflicts. The tests work too.

**Comment by seanauriti** [comment]
Thank you!

**Pull request merged**
