### PR TITLE
Functionality to see all bugs of the domain, if it exists

### PR DESCRIPTION
**Pull request by sid22**
Solves #145 . 
When the user goes to https://www.bugheist.com/report/ there a button is added below field for entering URL to check in db if bugs there for the domain entered.

Screenshots for way it works.

Case 1:
When bugs for the given domain exist:-
fe1
fe2

Case 2:
When bugs for the given domain don't exist:-
fe3

### CODE REVIEW

**Comment by goyal-sidd** [comment]
Also @jajodiaraghav the form has CSRF however, while sending the POST request through AJAX to the function I have added a CSRF exempt. Is it alright? Since it's only a domain field.

**Comment by jajodiaraghav** [comment]
@goyal-sidd No we do not need csrf for such ajax calls.
As mentioned earlier, you should never keep the code commented out in a commit, you must remove them before pushing since they are of no use.
Secondly, The styling of button and the message does not look right. You might want to fix those after this gets merged

**Comment by goyal-sidd** [comment]
Removed comments, will ensure it doesn't get repeated. 
I will work on the styling on another issue.

**Review by souravbadami — APPROVED** [review]

**Comment by jajodiaraghav** [comment]
This PR has some serious bugs. I don't understand why was it merged.

capture

@goyal-sidd Please fix this ASAP. Also, I can see some comments and console.log within the code, please remove them.

One more thing, you must learn the concepts of git `rebase` and `squash`. Please google these.

**Pull request merged**
