### PR TITLE
Added icons to the sidebar

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**
Issue #1684 

Screenshot-
image

I am not sure what to add on experimental options!

### CODE REVIEW

**Comment by DonnieBLT** [comment]
Can you use SVGs or font awesome? Because the images won't scale that well.

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Please use svg or fontawesome

**Comment by Prakhar-Shankar** [comment]
> Please use svg or fontawesome
Sure sir

**Comment by Prakhar-Shankar** [comment]
Changed to fontawesome

image

**Comment by DonnieBLT** [comment]
How about the four in the middle?

**Pull request closed without merging**
