### PR TITLE
Enhancement: Profile page

### PR DESCRIPTION
**Pull request by CodeWithBishal**
Fix some overflow issues in the design of profile page
added an edit button to edit user's crypto address

### CODE REVIEW

**Comment by CodeWithBishal** [comment]
@DonnieBLT can we keep both of the options? because this PR also contains design adjustments for the profile page to fix overflow issue

**Comment by CodeWithBishal** [comment]
Yep it should work with the current profile edit option

**Comment by CodeWithBishal** [comment]
@DonnieBLT after the merge I just need to make a few changes and "edit profile" should work fine with this PR

**Comment by CodeWithBishal** [comment]
right now, in my PR the `update_bch_address` is expecting a JSON payload which is not the case in the "edit profile" page, need to adjust this and it should work just fine

**Comment by CodeWithBishal** [comment]
ok

**Comment by CodeWithBishal** [comment]
I have made the required changes, please review @DonnieBLT

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
