### PR TITLE
Deleted the pyc files from comments app

### PR DESCRIPTION
**Pull request by mohitanand001**

### CODE REVIEW

**Comment by seanauriti** [comment]
ImportError: No module named comments

**Comment by farziengineer** [comment]
might be problem in settings.py. I'll check again.

**Comment by farziengineer** [comment]
The problem is there because the __init__.py of the comments app is empty and hence can't be uploaded on github.

**Comment by seanauriti** [comment]
Should be able too. Maybe add a #

**Comment by farziengineer** [comment]
Okay

**Pull request merged**
