### PR TITLE
Fix #140: Handling duplicate/non bug.

### LINKED ISSUE #140: Have points deduction for duplicate / non bug

### PR DESCRIPTION
**Pull request by mohitanand001**

### CODE REVIEW

**Review by souravbadami — CHANGES_REQUESTED** [review]
Hi @farziengineer -- I'm continuously getting these error responses on the console. Could you please fix it first ?

`Not Found: /issue/1/None`
`Not Found: /issue/1/None`
`[09/Jun/2017 16:00:47] "GET /issue/1/None HTTP/1.1" 404 6414`
`[09/Jun/2017 16:00:54] "GET / HTTP/1.1" 200 23327`
`[09/Jun/2017 16:00:54] "GET /media/screenshots/abcde.png HTTP/1.1" 304 0`.

**Comment by farziengineer** [comment]
@souravbadami Can you please tell how to reproduce it.

**Comment by souravbadami** [comment]
Just look into the logs while opening the index and issue page.

**Comment by farziengineer** [comment]
I am getting those  only when I am clicking the "Report the user" button. In index page I didn't get though.
I've fixed it by using HTTP Referrer. Let's see if it solves for you.

**Comment by souravbadami** [comment]
I don't see your latest changes here. Have you pushed the new commit ?

**Comment by souravbadami** [comment]
The issue with 404 is something irrelevant to your feature. But, I'm not sure why you used *HTTP Referrer* to solve it ? It's being handled on #268.

For your feature, it's more related to the design. Why is **Admin** automatically giving **4+** points to the user who reports if a bug is duplicate (maybe a fake claim). I think, the **Admin** has to manually agree with the user and if it's fine, **4+** points should be awarded. Until then, it should be somewhere in an admin panel where **Admin** can monitor a list of duplicate reported bugs. Let me know your opinion.

**Comment by farziengineer** [comment]
@souravbadami . I think  this would be fine. It was already decided by @seanauriti in the slack conversation.

**Comment by souravbadami** [comment]
Hi @farziengineer -- I just had a discussion with **Sean** and we agreed upon moving to the moderation procedure as I mentioned before. Please let me know when you complete that feature and push the new changes.

**Comment by seanauriti** [comment]
Can you please reopen this and we can get this feature done?

**Pull request closed without merging**
