### PR TITLE
Contribution stats colour adjustments 

### LINKED ISSUE #1970: Contribution stats color is too dark
image

### PR DESCRIPTION
**Pull request by HanilJain**
### Fixed #1970 

Screenshot 2024-03-08 171252

### CODE REVIEW

**Review by DonnieBLT — APPROVED** [review]

**Comment by HanilJain** [comment]
@DonnieBLT

**Comment by HanilJain** [comment]
@DonnieBLT 

Screenshot 2024-03-08 235407

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Please see feedback

**Comment by HanilJain** [comment]
image
@DonnieBLT ??

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
