### PR TITLE
Issue #1529

### PR DESCRIPTION
**Pull request by manthan0x23**
# Issue #1529 

--fixed flex display in the buttons area
--Icons resized to regular 
--truncation done for mobile view

Screenshot from 2023-10-29 20-06-52
Screenshot from 2023-10-29 20-07-05

Please review

### CODE REVIEW

**Comment by manthan-sharma-23** [comment]
Hey I  have also fixed the UI for the profile card 
Kindly review that too Thank You!

Untitled

**Review by DonnieBLT — APPROVED** [review]

**Comment by DonnieBLT** [comment]
Can you make a new PR please? This branch can't be rebased.

**Comment by manthan-sharma-23** [comment]
Uh yeah sure....can I make it by today eve...not at workspace right now.

**Comment by manthan-sharma-23** [comment]
Hey @DonnieBLT  kindly check if the conflicts have been resolved . Thank you !

**Review by DonnieBLT — APPROVED** [review]

**Comment by DonnieBLT** [comment]
Getting this error image

**Comment by manthan-sharma-23** [comment]
uhh so should i try to make a new PR only ?

**Comment by DonnieBLT** [comment]
Yes I think that will work.

**Pull request closed without merging**
