### PR TITLE
Removed tweets block.

### PR DESCRIPTION
**Pull request by souravbadami**

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
This looks good. Are you sure we should remove the tweets block?
@seanauriti

**Comment by souravbadami** [comment]
@jajodiaraghav -- I had a discussion with **Sean** and we agreed on removing it from the home.

**Comment by seanauriti** [comment]
I kind of like it because it shows that we tweeted it.  Anyone else have an opinion on it?

**Comment by jajodiaraghav** [comment]
I think @souravbadami has a point. But if @seanauriti want to keep it, maybe we should place it somewhere else to make it a win win. Any suggestions?

**Comment by souravbadami** [comment]
How about moving it to another page, called **social feeds**. Then, we can put it there in a column initially and then we can also add a Facebook feed by doing the same thing (posting issues on Facebook) ?

**Comment by seanauriti** [comment]
Sounds good to me!

**Comment by jajodiaraghav** [comment]
Sounds good!
Should this be merged then? We can create the social page in a different commit.

**Comment by souravbadami** [comment]
Yes, let's merge this.

**Review by jajodiaraghav — APPROVED** [review]

**Pull request merged**
