### PR TITLE
List like

### PR DESCRIPTION
**Pull request by mohitanand001**
screenshot from 2017-09-08 01 19 45

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Why is the same PR made twice? One exactly similar PR #551 already got merged

**Comment by farziengineer** [comment]
sorry it was a mistake

**Comment by jajodiaraghav** [comment]
I cannot find the "Liked by" modal in /issue. Please check

**Comment by farziengineer** [comment]
Actually the other PR not on the master of OWASP/BLT hence this needs to merged.

**Review by jajodiaraghav — APPROVED** [review]

**Comment by jajodiaraghav** [comment]
@farziengineer I just saw that you have opened several unnecessary branches in the main BLT repository. This kind of mistakes happen when you do not understand the git workflow. I have closed them. Make sure to prevent making new branches while creating pulls

**Pull request merged**
