### PR TITLE
add a small tip button on the leaderboard that opens the QR code for the users BCH address #1819

### PR DESCRIPTION
**Pull request by Sarthak5598**
#1819

### CODE REVIEW

**Review by HanilJain — COMMENTED** [review]
@Sarthak5598  **To add Tip button** 
suggestion : to add tip button you can replace the rank span and replace it with the tip button.
and rank can be displayed over the avatar of the user and really small so that it does not cover the avatar but enough readable

**Comment by DonnieBLT** [comment]
That sounds like a good idea. Can we see a screenshot of this when it's ready please

**Comment by Sarthak5598** [comment]
Something like this thanks to @HanilJain for the idea 
Screenshot 2024-02-29 010252

**Comment by Sarthak5598** [comment]
I still have 1 issue the tip button is also taking us to user profile as its under anchor tag and if I move it out of anchor tag it goes to next line

**Comment by HanilJain** [comment]
> Something like this thanks to @HanilJain for the idea Screenshot 2024-02-29 010252

@Sarthak5598 Awesome. it would look even better if you add colour to rank like gold , silver and bronze.

**Comment by HanilJain** [comment]
> I still have 1 issue the tip button is also taking us to user profile as its under anchor tag and if I move it out of anchor tag it goes to next line

make that a div and tip in a anchor tag

**Comment by Sarthak5598** [comment]
it worked @HanilJain thanks a lot !!!

**Review by DonnieBLT — APPROVED** [review]

**Pull request merged**
