### PR TITLE
Fixed High Response Time in Scoreboard API

### PR DESCRIPTION
**Pull request by srahulbadami**

### CODE REVIEW

**Comment by souravbadami** [comment]
@srahulbadami -- Ready to merge ?

**Comment by souravbadami** [comment]
@srahulbadami -- Any updates on this ?

**Comment by srahulbadami** [comment]
Working on it

**Review by fredfalcon — APPROVED** [review]

**Comment by souravbadami** [comment]
@fredfalcon -- We can't merge it unless the test passes.

**Review by souravbadami — DISMISSED** [review]
@srahulbadami -- Please look into it. Tests are failing apparently.

**Comment by srahulbadami** [comment]
Yes. Looking into it

**Pull request merged**
