### PR TITLE
Added API to get userscores and added new serialisers. 

### PR DESCRIPTION
**Pull request by srahulbadami**

### CODE REVIEW

**Comment by souravbadami** [comment]
@srahulbadami -- The tests are failing, could you check ? Probably because of `djangorestframework-filters` dependency.

**Review by souravbadami — CHANGES_REQUESTED** [review]
Comment added.

**Comment by srahulbadami** [comment]
@souravbadami @fredfalcon  Test is passed . can you check ?

**Review by souravbadami — APPROVED** [review]

**Comment by fredfalcon** [comment]
Can you please update the Pipfile.lock?

-----> Python app detected
-----> Found python-3.6.4, removing
-----> Installing python-3.6.5
-----> Installing pip
-----> Installing dependencies with Pipenv 11.8.2…
       Your Pipfile.lock (89438e) is out of date. Expected: (aabdb1).
       Aborting deploy.
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Pull request merged**
