### PR TITLE
Hide all issues feature

### LINKED ISSUE #1032: allow user's posted issues to be hidden

### PR DESCRIPTION
**Pull request by Kej-r03**
Fixes #1032. I have implemented the hide all issues feature (see below user profile pic). When it is checked, nobody except the user, can view his issues anywhere on Bugheist.

photo_2023-02-25_18-06-45

### CODE REVIEW

**Comment by Kej-r03** [comment]
@fredfalcon please review the feature, so I can extend this to hiding individual issues and complete domain issues as well

**Comment by Kej-r03** [comment]
Can you please confirm if there are any pending changes or this PR is good to merge

**Review by fredfalcon — APPROVED** [review]

**Comment by Kej-r03** [comment]
> Looks good! What happens if someone lands on a hidden issue page? Can we return a 404?

No I had not taken that into consideration. Will work on that

**Comment by Kej-r03** [comment]
I think you can create it as a separate issue, I will try to work it out in a couple of days

**Pull request merged**
